<?php


namespace App\Http\Request;


use Illuminate\Foundation\Http\FormRequest;

class BetLoginPost extends FormRequest
{
    /**
     * 确定用户是否有权发出此请求
     **/
    public function authorize(){
        return true;
    }
    /**
     * 获取适用于请求的验证规则
     **/
    public function rules(){
        return [
            //
            'account'=>'required',
            'password'=>'required'
        ];
    }
    public function messages(){
        return [
            'account.required'=>"账号不能为空",
            'password.required'=>'密码不能为空'
        ]; // TODO: Change the autogenerated stub
    }
}
